#!/usr/bin/with-contenv bash

# copy config
if [[ ! -e /config/sync.conf ]]; then
    cp /defaults/sync.conf /config/sync.conf
fi

# permissions
lsiown -R abc:abc \
    /config

lsiown abc:abc \
    /sync
